-- MySQL Script generated by MySQL Workbench
-- Tue Dec 25 19:26:23 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`website`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`website` (
  `id` INT NOT NULL,
  `url` VARCHAR(512) NULL,
  `added` DATETIME NULL,
  `lastChecked` DATETIME NULL,
  `domainName` VARCHAR(256) NULL,
  `domainExtension` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ledger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ledger` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fakeWebshop` INT NULL,
  `ipAddress` VARCHAR(64) NULL,
  `httpsAvailable` TINYINT NULL,
  `screenshotUrl` TEXT NULL,
  `checked` DATETIME NULL,
  `live` TINYINT NULL,
  `notFakeAnymore` TINYINT NULL,
  `fakeScore` FLOAT NULL,
  `certificateCheck` VARCHAR(256) NULL,
  `headers` JSON NULL,
  `responseCode` INT NULL,
  `website_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ledger_website_idx` (`fakeWebshop` ASC),
  CONSTRAINT `fk_ledger_website`
    FOREIGN KEY (`fakeWebshop`)
    REFERENCES `mydb`.`website` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alias` (
  `id` INT NOT NULL,
  `domein` INT NOT NULL,
  `domeinnaam` VARCHAR(256) NULL,
  `domeinExtensie` VARCHAR(20) NULL,
  `httpsAanwezig` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_alias_website1_idx` (`domein` ASC),
  CONSTRAINT `fk_alias_website1`
    FOREIGN KEY (`domein`)
    REFERENCES `mydb`.`website` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`webshop-good`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`webshop-good` (
  `id` INT NOT NULL,
  `website` INT NOT NULL,
  `httpsAanwezig` TINYINT NULL,
  `email` VARCHAR(256) NULL,
  `vestigingsAdres` TEXT NULL,
  `postAdres` TEXT NULL,
  `telefoonNummer` VARCHAR(128) NULL,
  `bedrijfsNaam` VARCHAR(256) NULL,
  `kvkNummer` INT NULL,
  `btwNummer` VARCHAR(256) NULL,
  `contactPersoon` VARCHAR(256) NULL,
  `added` DATETIME NULL,
  `live` TINYINT NULL,
  `keurmerk` TINYINT NULL,
  `keurmerkNaam` VARCHAR(256) NULL,
  `keurmerkLidSinds` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_webshop-good_website1_idx` (`website` ASC),
  CONSTRAINT `fk_webshop-good_website1`
    FOREIGN KEY (`website`)
    REFERENCES `mydb`.`website` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `username` VARCHAR(64) NULL,
  `password` VARCHAR(2048) NULL,
  `jwtToken` VARCHAR(2048) NULL,
  `accountMade` DATETIME NULL,
  `lastLogin` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
